global proc FilePathLocator() {};

string $locatorInfo = `whatIs FilePathLocator`;
string $filePath = `substring $locatorInfo 25 999`;
string $pluginDir = `dirname $filePath`;

string $PythonCmd = "import sys;";
$PythonCmd += "sys.path.append('" + $pluginDir + "');";
$PythonCmd += "import install;";
$PythonCmd += "import importlib;";
$PythonCmd += "importlib.reload(install);";
$PythonCmd += "install.Install()";

python($PythonCmd);